name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Prepare
        run: |
          sed -i "s/[[token]]/{{ secrets.GH_RUNNER_TOKEN }}/" build/builder/.npmrc

      - name: Build
        run: |
          cd build
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}/base base
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/base
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}/runner runner
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/runner
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}/deployer deployer
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/deployer
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}/builder --secret id=npmrc,src=builder/.npmrc builder
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/builder
  deploy:
    runs-on: deployer
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        run: |
          helm upgrade --install -n runner-system runner chart/ --set token=${{ secrets.GH_RUNNER_TOKEN }}
